CREATE TABLE IF NOT EXISTS employees (
    employee_id VARCHAR(36) PRIMARY KEY,
    auth0_id VARCHAR(128) NOT NULL UNIQUE,
    email_address VARCHAR NOT NULL UNIQUE,
    first_name VARCHAR NOT NULL,
    middle_name VARCHAR,
    last_name VARCHAR NOT NULL,
    phone_number VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    hire_date DATE NOT NULL,
    picture VARCHAR,
    language VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    city VARCHAR NOT NULL,
    zipcode VARCHAR NOT NULL,
    salary INTEGER NOT NUll,
    position VARCHAR NOT NULL,
    emergency_contact_name VARCHAR,
    emergency_contact_email VARCHAR,
    emergency_contact_phone VARCHAR,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);
