// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	rabbitmq "github.com/wagslane/go-rabbitmq"
)

// RabbitmqAdapter is an autogenerated mock type for the rabbitmqAdapter type
type RabbitmqAdapter struct {
	mock.Mock
}

// Publish provides a mock function with given fields: message, routingKey, options
func (_m *RabbitmqAdapter) Publish(message []byte, routingKey []string, options ...func(*rabbitmq.PublishOptions)) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, message, routingKey)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
